<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="srstyle.css">
</head>
<body>
   
    <div class="andtop" onclick ="arr()"></div>
    <div class="wrap"><form method="POST" action="view.PHP"><input type="text" class="search" name="srh" placeholder="Enter the title of the book"><input type="submit" name="find" value="search" class="button-33"  ></form></div>
<script type="text/javascript" src="anim .js"></script>

</body>

</html>